version: '3.8'

services:
  pixqrcode:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./static/qrcodes:/app/static/qrcodes
    environment:
      - FLASK_ENV=development
    networks:
      - smart_parking
networks:
  smart_parking:
    external: true
